name: Build and Test Images

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14

    env:
      BREW_BASH_PATH: /usr/local/bin/bash

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Install Bash version 5.x on macOS to improve script stability
        shell: bash
        run: |
          brew install bash
          echo "PATH=${BREW_BASH_PATH}:$PATH" >> $GITHUB_ENV

      - name: Check the version of Bash
        run: bash --version

      - name: Check that the GitHub Actions 'shell' instruction uses the updated Bash
        shell: bash
        run: echo "This is another test script running in Bash version $BASH_VERSION"
