name: CI - Build and Test Images
on: [push, pull_request]

jobs:
  generate-matrix:
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate the matrix
        run: |
          pip install jq
          python scripts/generate_matrix.py

      - name: Verify matrix.json
        run: |
          cat matrix.json | jq -c .
          jq empty matrix.json

      - name: Save the matrix strategy
        id: set-matrix
        run: echo "matrix=$(cat matrix.json | jq -c .)" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Install Just so that justfile shortcuts are supported
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the Docker Images
        run: |
          docker buildx create --use
          ./scripts/build_image.sh \
              -p ${{ matrix.platform }} \
              -i ${{ matrix.image }} \
              -v ${{ matrix.image_version }} \
              -a ${{ matrix.s6_architecture }} \
              --save

      - name: Set correct permissions for the artifacts
        run: sudo chmod -R 755 ./*.tar

      - name: Upload Docker Images as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}_${{ matrix.image_version }}_${{ matrix.s6_architecture }}
          path: ${{ matrix.image }}_${{ matrix.image_version }}_${{ matrix.s6_architecture }}.tar
          retention-days: 30

      - name: Print the Docker Images (for logging purposes)
        run: just list-local-image-architectures
