name: Build and Test Images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      BREW_BASH_PATH: /usr/local/bin/bash
      REPO_ADDRESS: webdavis/docker-s6-overlay

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Check the current version of Bash on Ubuntu 24.04
        run: bash --version

      - name: Install Just so that justfile shortcuts are supported
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #
      # - name: Test Docker Buildx
      #   run: |
      #     docker buildx create --use
      #     docker buildx build \
      #       --load \
      #       --platform "linux/amd64" \
      #       --build-arg IMAGE_VERSION="3.19" \
      #       --build-arg S6_OVERLAY_VERSION="3.1.6.2" \
      #       --build-arg S6_OVERLAY_ARCHITECTURE="x86_64" \
      #       --tag "${REPO_ADDRESS}:alpine-3.19-x86_64-3.1.6.2" \
      #       -f "Dockerfile.alpine" .
      #
      # - name: Print Docker Images
      #   run: just list-local-image-architectures
