name: Build and Test Images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      BREW_BASH_PATH: /usr/local/bin/bash
      REPO_ADDRESS: webdavis/docker-s6-overlay

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Check the current version of Bash on Ubuntu 24.04
        run: bash --version

      - name: Install Just so that justfile shortcuts are supported
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Alpine Docker Image using build script
        run: |
          docker buildx create --use
          ./scripts/build_image.sh -p "linux/amd64" -i "alpine" -v "3.19" -a "x86_64"

      - name: Print Docker Images
        run: just list-local-image-architectures
