name: Build and Test Images

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Check version of Bash
        shell: bash
        run: bash --version
