name: CD - Deploy Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Install project dependencies
        run: sudo apt-get update && sudo apt-get install -y parallel jq just

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Enable Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Bootstrap a new Docker builder instance
        run: just bootstrap-docker-builder

      - name: Build and push the Docker Images and their manifests upstream
        run: just push-images-in-parallel

      # - name: Verify remote image architectures using image manifests
      #   run: just list-remote-image-architectures
