name: CD - Deploy images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Install project dependencies
        run: sudo apt-get update && sudo apt-get install -y parallel jq just

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Enable Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Bootstrap a new Docker builder instance
        run: just bootstrap-docker-builder

      - name: Build and push the Docker Images and their manifests upstream
        run: just push-images-in-parallel

      - name: Check for changes in official_image_metadata.json
        run: |
          if git diff --name-only | grep -q "official_image_metadata.json"; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes if official_image_metadata.json is updated
        if: env.changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add official_image_metadata.json
          git commit -m "deploy: updated official_image_metadata.json"
          git push
