name: Deploy Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Install Bash script dependencies
        run: sudo apt-get update && sudo apt-get install -y parallel jq

      - name: Install Just so that justfile shortcuts are supported
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y just

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: webdavis
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Add support for more platforms with QEMU.
        # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU virtualization for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Create a new Docker builder instance
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap

      - name: Build a Docker Image
        run: ./scripts/build_image.sh -p linux/amd64 -i ubuntu -v 24.04 -a x86_64

      - name: Push the Docker Image
        run: docker push webdavis/docker-s6-overlay:ubuntu-24.04-x86_64-3.1.6.2

      - name: Verify remote image architectures using image manifests
        run: just list-remote-image-architectures
